linters:
  enable:
    - errcheck
    - gocritic
    - gosec
    - govet
    - misspell
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
  gosec:
    excludes:
      - G115
      - G306
      - G404
  gocritic:
    disabled-checks:
      - ifElseChain
      - appendAssign

issues:
  exclude-dirs:
    - testdata
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
